[build]
  command = "cd frontend/url-shortener-client-side && npm install && npm run build"
  publish = "frontend/url-shortener-client-side/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  conditions = {Path = ["/add-url/*", "/:url/*"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200